---
- name: copy .my.cnf
  template: src=.my.cnf dest=/root/.my.cnf owner=root mode=0600

- name: add password to root account
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT login_user=root log
  with_items:
    - "{{ inventory_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: remove anonymous users
  mysql_user: name='' host={{ item }} state=absent login_user=root login_password={{ mysql_root_password }}
  with_items:
    - localhost
    - "{{ inventory_hostname }}"

- name: remove test tables
  mysql_db: name=test state=absent login_user=root login_password={{ mysql_root_password }}
